# Generated by Django 4.1 on 2024-03-11 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateTimeField()),
                ('Gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=255)),
                ('Address', models.TextField(max_length=250)),
                ('Photo', models.BinaryField(max_length='max')),
                ('Departament', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.department')),
                ('Position', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('technique', models.CharField(choices=[('DAI', 'Desarrollo y Administración de Aplicaciones Informáticas'), ('GAT', 'Gestión y Administración Tributaria'), ('CM', 'Comercio y Mercadeo'), ('G', 'Gastronomía'), ('E', 'Electrónica'), ('EL', 'Electricidad'), ('RAA', 'Refrigeración y Acondicionamiento de Aire')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateTimeField()),
                ('Gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=255)),
                ('Address', models.TextField(max_length=250)),
                ('Photo', models.BinaryField(max_length='max')),
                ('Technique', models.CharField(choices=[('DAI', 'Desarrollo y Administración de Aplicaciones Informáticas'), ('GAT', 'Gestión y Administración Tributaria'), ('CM', 'Comercio y Mercadeo'), ('G', 'Gastronomía'), ('E', 'Electrónica'), ('EL', 'Electricidad'), ('RAA', 'Refrigeración y Acondicionamiento de Aire')], max_length=255)),
                ('Course', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.CharField(max_length=100)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Main_contact', models.CharField(max_length=255)),
                ('Second_contact', models.CharField(max_length=255)),
                ('Address', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='tecnicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=100)),
                ('CF', models.IntegerField(default=0)),
                ('RA1', models.IntegerField()),
                ('RA2', models.IntegerField()),
                ('RA3', models.IntegerField()),
                ('RA4', models.IntegerField()),
                ('RA5', models.IntegerField()),
                ('RA6', models.IntegerField()),
                ('RA7', models.IntegerField()),
                ('RA8', models.IntegerField()),
                ('RA9', models.IntegerField()),
                ('RA10', models.IntegerField()),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.moduletechnique')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField(blank=True)),
                ('Evaluation', models.CharField(max_length=100)),
                ('Hours_so_far', models.IntegerField()),
                ('Hours_to_complete', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('Student', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Supervisor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_information', models.TextField(max_length=250)),
                ('Student', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Tutor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='academicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=100)),
                ('CF', models.IntegerField(default=0)),
                ('Subject', models.CharField(choices=[('M', 'Matemáticas'), ('N', 'Naturales'), ('S', 'Sociales'), ('I', 'Inglés'), ('Ë', 'Español'), ('A', 'Arte'), ('ED', 'Educación física'), ('REL', 'Religión'), ('O', 'Otro')], default='O', max_length=100)),
                ('P1', models.IntegerField()),
                ('P2', models.IntegerField()),
                ('P3', models.IntegerField()),
                ('P4', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
