# Generated by Django 4.1 on 2024-03-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateTimeField()),
                ('Gender', models.CharField(max_length=255)),
                ('Address', models.TextField(max_length=250)),
                ('Photo', models.BinaryField()),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateTimeField()),
                ('Gender', models.CharField(max_length=255)),
                ('Address', models.TextField(max_length=250)),
                ('Photo', models.BinaryField()),
                ('Tecnica', models.CharField(max_length=255)),
                ('Curso', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
