# Generated by Django 4.1 on 2024-03-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateTimeField()),
                ('Gender', models.CharField(max_length=255)),
                ('Address', models.TextField(max_length=250)),
                ('Photo', models.BinaryField(max_length='max')),
                ('Technique', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Birthdate', models.DateTimeField()),
                ('Gender', models.CharField(max_length=255)),
                ('Address', models.TextField(max_length=250)),
                ('Photo', models.BinaryField(max_length='max')),
                ('Cargo', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.cargo')),
                ('Departamento', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
