# Generated by Django 4.1 on 2024-03-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
