# Generated by Django 4.1 on 2024-03-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Photo',
        ),
        migrations.AddField(
            model_name='employee',
            name='Photo_URL',
            field=models.CharField(default='https://example.com/placeholder_image.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Photo_URL',
            field=models.CharField(default='https://example.com/placeholder_image.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Course',
            field=models.CharField(choices=[('4_DAI_A', '4to Desarrollo y Administración de Aplicaciones Informáticas Sección A'), ('5_DAI_A', '5to Desarrollo y Administración de Aplicaciones Informáticas Sección A'), ('6_DAI_A', '6to Desarrollo y Administración de Aplicaciones Informáticas Sección A'), ('4_GAT_A', '4to Gestión y Administración Tributaria Sección A'), ('4_GAT_B', '4to Gestión y Administración Tributaria Sección B'), ('5_GAT_A', '5to Gestión y Administración Tributaria Sección A'), ('5_GAT_B', '5to Gestión y Administración Tributaria Sección B'), ('6_GAT_A', '6to Gestión y Administración Tributaria Sección A'), ('6_GAT_B', '6to Gestión y Administración Tributaria Sección B'), ('4_CM_A', '4to Comercio y Mercadeo Sección A'), ('4_CM_B', '4to Comercio y Mercadeo Sección B'), ('5_CM_A', '5to Comercio y Mercadeo Sección A'), ('5_CM_B', '5to Comercio y Mercadeo Sección B'), ('6_CM_A', '6to Comercio y Mercadeo Sección A'), ('6_CM_B', '6to Comercio y Mercadeo Sección B'), ('4_G_A', '4to Gastronomía Sección A'), ('5_G_A', '5to Gastronomía Sección A'), ('6_G_A', '6to Gastronomía Sección A'), ('4_E_A', '4to Electrónica Sección A'), ('5_E_A', '5to Electrónica Sección A'), ('6_E_A', '6to Electrónica Sección A'), ('4_EL_A', '4to Electricidad Sección A'), ('5_EL_A', '5to Electricidad Sección A'), ('6_EL_A', '6to Electricidad Sección A'), ('4_RAA_A', '4to Refrigeración y Acondicionamiento de Aire Sección A'), ('5_RAA_A', '5to Refrigeración y Acondicionamiento de Aire Sección A'), ('6_RAA_A', '6to Refrigeración y Acondicionamiento de Aire Sección A')], max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=255),
        ),
    ]
