# Generated by Django 4.1 on 2024-03-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Birthdate',
            field=models.DateField(),
        ),
    ]
