# Generated by Django 4.1 on 2024-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Technique',
            new_name='technique',
        ),
        migrations.AddField(
            model_name='student',
            name='rne',
            field=models.CharField(default='JD05050000', max_length=12, unique=True),
        ),
    ]
