# Generated by Django 4.1 on 2024-04-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0002_rename_course_student_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='rne',
            new_name='RNE',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='technique',
            new_name='Technique',
        ),
    ]
