# Generated by Django 4.1 on 2024-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0002_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
