# Generated by Django 4.1 on 2024-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0002_remove_employee_photo_remove_student_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Photo_URL',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='student',
            name='Photo_URL',
            field=models.CharField(max_length=4000),
        ),
    ]
