# Generated by Django 4.1 on 2024-04-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0003_rename_course_student_course_rename_rne_student_rne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RNE',
            field=models.CharField(default='JD05050000', max_length=13, unique=True),
        ),
    ]
