# Generated by Django 4.1 on 2024-03-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0003_alter_activities_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_information', models.TextField(max_length=250)),
                ('Student', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Tutor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.tutor')),
            ],
        ),
    ]
