# Generated by Django 4.1 on 2024-03-10 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0003_alter_activities_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descripcion',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='nombre',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='estado',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Departamento',
            new_name='Departament',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Cargo',
            new_name='Position',
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Evaluation', models.JSONField()),
                ('Hours_so_far', models.IntegerField()),
                ('Hours_to_complete', models.IntegerField()),
                ('Status', models.BooleanField()),
                ('Student', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Supervisor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pomaray.employee')),
            ],
        ),
    ]
