# Generated by Django 4.1 on 2024-03-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0003_alter_employee_photo_url_alter_student_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
