# Generated by Django 4.1 on 2024-03-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0003_alter_activities_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='tecnicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=100)),
                ('CF', models.IntegerField(default=0)),
                ('Module', models.CharField(max_length=100)),
                ('RA1', models.IntegerField()),
                ('RA2', models.IntegerField()),
                ('RA3', models.IntegerField()),
                ('RA4', models.IntegerField()),
                ('RA5', models.IntegerField()),
                ('RA6', models.IntegerField()),
                ('RA7', models.IntegerField()),
                ('RA8', models.IntegerField()),
                ('RA9', models.IntegerField()),
                ('RA10', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='acadmicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.CharField(max_length=100)),
                ('CF', models.IntegerField(default=0)),
                ('Subject', models.CharField(choices=[('M', 'Matemáticas'), ('N', 'Naturales'), ('S', 'Sociales'), ('I', 'Inglés'), ('Ë', 'Español'), ('A', 'Arte'), ('ED', 'Educación física'), ('REL', 'Religión'), ('O', 'Other')], default='O', max_length=100)),
                ('P1', models.IntegerField()),
                ('P2', models.IntegerField()),
                ('P3', models.IntegerField()),
                ('P4', models.IntegerField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.student')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomaray.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
