# Generated by Django 4.1 on 2024-03-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0004_alter_employee_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Departament',
            field=models.CharField(choices=[('HR', 'Recursos Humanos'), ('ACCS', 'Finanzas y Contabilidad'), ('RGS', 'Admisiones y Registro'), ('MTE', 'Limpieza y Mantenimiento'), ('SCY', 'Seguridad y Bienestar'), ('PSY', 'Psicologia'), ('VCN', 'Vinculación Sectorial'), ('ADT', 'Administracion y Coordinación'), ('EDT', 'Docencia'), ('LBR', 'Biblioteca')], max_length=100),
        ),
    ]
