# Generated by Django 4.1 on 2024-03-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0004_tecnicqualification_acadmicqualification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acadmicQualification',
            new_name='academicQualification',
        ),
    ]
