# Generated by Django 4.1 on 2024-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0004_alter_student_rne'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Sur_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='Sur_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
