# Generated by Django 4.1 on 2024-03-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0004_employee_full_name_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
