# Generated by Django 4.1 on 2024-03-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0005_alter_employee_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Position',
            field=models.CharField(choices=[('PR', 'Director'), ('SCT', 'Secretaria'), ('TEA', 'Profesor'), ('PSY', 'Psicologo'), ('LBR', 'Bibliotecario'), ('JNR', 'Conserje'), ('SPR', 'Encargado'), ('SCG', 'Guardia de Seguridad')], max_length=100),
        ),
    ]
