# Generated by Django 4.1 on 2024-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0005_alter_internship_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='End_Date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Evaluation',
            field=models.JSONField(),
        ),
    ]
