# Generated by Django 4.1 on 2024-03-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomaray', '0004_emergency'),
        ('pomaray', '0005_rename_acadmicqualification_academicqualification'),
        ('pomaray', '0007_alter_internship_evaluation'),
    ]

    operations = [
    ]
