# Generated by Django 4.1 on 2024-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo_url',
            field=models.CharField(default='http://joedoes.com/', max_length=300),
        ),
    ]
