# Generated by Django 4.1 on 2024-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customuser_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_url',
            field=models.CharField(default='https://i.pinimg.com/564x/18/b5/b5/18b5b599bb873285bd4def283c0d3c09.jpg', max_length=300),
        ),
    ]
