# Generated by Django 4.1 on 2024-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.CharField(default='https://pbs.twimg.com/media/FOJS-LzXwAAV3aO.jpg:large', max_length=500),
        ),
    ]
