# Generated by Django 4.1 on 2024-04-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(default='post_cover_photos/default.jpg', upload_to='post_cover_photos/'),
        ),
    ]
